# Generated by Django 4.0 on 2021-12-22 21:57
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0015_auto_20211222_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('typeOfLeave', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Leave Request Type greater than 2 char')])),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='status greater than 2 char')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaevRequest', to='authentication.user')),
            ],
        ),
    ]