# Generated by Django 4.0 on 2021-12-22 01:04

from django.db import migrations


class Migration(migrations.Migration):
    def defaultWeekend(apps,schema_editor):
        weekend = apps.get_model('weekend','weekend')
        weekend.objects.create(
            saturday = False,
            sunday = False,
            monday = False,
            tuesday = False,
            wendesday = False,
            thursday = False,
            friday = False,
        )

    dependencies = [
        ('weekend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(defaultWeekend)
    ]
