# Generated by Django 4.0 on 2021-12-19 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('roleName', models.CharField(max_length=30, unique=True)),
                ('roleDesc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
