# Generated by Django 4.0 on 2021-12-22 00:34

from django.db import migrations


class Migration(migrations.Migration):
    def defaultRole(apps,schema_editor):
        role = apps.get_model('role','role')
        role.objects.create(
            roleName='manager',
            roleDesc='managing all the app'
        )
        role.objects.create(
            roleName='employer',
            roleDesc='only can watch dont do anything'
        )

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(defaultRole)
    ]
