# Generated by Django 3.2.8 on 2021-12-13 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=12, message='Phone Number must be 12 number'), django.core.validators.RegexValidator(message='must be valid Egyption Number', regex='01[1,2,5,0]{1}[0-9]{8}')], verbose_name='phone number'),
        ),
    ]
