# Generated by Django 4.0 on 2021-12-14 20:46

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', authentication.models.MyUserManager()),
            ],
        ),
    ]
