# Generated by Django 4.0 on 2021-12-21 21:52

from django.db import migrations
from django.contrib.auth.hashers import make_password

class Migration(migrations.Migration):

    def defaultUser(apps,schema_editor):
        User = apps.get_model('authentication','User')
        User.objects.create_user(
            firstname="admin",
            lastname = "admin",
            username = "admin",
            email = "admin@gmail.com",
            password = "adminn",
            phoneNumber = "01111111111",
            nationalID = "11111111111111",
            is_active=True,
            is_staff = True,
            is_superuser = True,
            )

    dependencies = [
        ('authentication', '0014_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(defaultUser),
    ]
