# Generated by Django 4.0 on 2021-12-20 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('checkinMinTime', models.TimeField()),
                ('checkinMaxTime', models.TimeField()),
                ('checkoutMinTime', models.TimeField()),
                ('checkoutMaxTime', models.TimeField()),
                ('numOfLeaveRequest', models.IntegerField()),
            ],
        ),
    ]
