# Generated by Django 4.0 on 2021-12-21 22:28

from django.db import migrations


class Migration(migrations.Migration):
    def defaultSystemControl(apps,schema_editor):
        Control = apps.get_model('systemControl','Control')
        Control.objects.create(
            checkinMinTime= '08:00:00',
            checkinMaxTime = '09:00:00',
            checkoutMinTime = '17:00:00',
            checkoutMaxTime = '18:00:00',
            numOfLeaveRequest =6
        )
    dependencies = [
        ('systemControl', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(defaultSystemControl)
    ]
