# Generated by Django 4.0 on 2021-12-23 00:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0015_auto_20211222_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('didAttended', models.BooleanField(default=True)),
                ('checkIn', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('checkOut', models.TimeField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='authentication.user')),
            ],
        ),
    ]
